### ISSUE TITLE
Suggestion for improving UnklickySlideswipe accuracy due to bed flex on V0

### ISSUE THREAD

**Issue by vkvam** [chestwood96/SlideSwipe#4]
Hey! UnklickySlideswipe seems to have a really cool design, thanks for publishing it on Github!

I can't really see a lot of room for improvement on the probe itself, but I think it's possible to adapt it better to the infamous V0 bed flex.

I've been printing some really tiny parts with 0.2 mm nozzle and 0.1 mm layer height on my Voron 0.2 with Kirigami bed, and when applying a mesh I've noticed that the nozzle is closer to the bed the further away from the z rails it is.

Further more, if i get the probe to trigger on the front of the bed, I can actually see the bed flexing ever so slightly.

If I remove the centre magnet intended to push the plunger on to the screws from the probe, and align the plunger magnet so that the two attachment magnets pushes on it– the force required to push it is reduced drastically.

**Comment by vkvam** [comment]
![test_prints](https://user-images.githubusercontent.com/1622135/218690804-c15bd75e-fa40-4ec8-b4fb-393fe9e03e0e.jpg)

Just finished a test print... I did not expect this much of an improvement.

**Comment by chestwood96** [comment]
There is a lot of playing room with the magnet strengths though there are
some tradeoffs, weaker magnets have had the effect you are describing on my
testing too but at the cost of causing false positives a lot more often. I
ended up just using kirigami to mitigate this issue.

**Comment by vkvam** [comment]
Yeah, I‘m also using kirigami and tested a bit more, there is still is a 0.05-0.1mm diff between front and back of the bed when I run mesh. There must be another issue, unrelated to the probe, since it is so significant and it’s not a big topic among klicky/v0 users.

I’m thinking the pros of the suggestion may apply specifically to whatever issue I’m having, and that the cons outweighs them for anyone else, so I’ll close the issue.
