### ISSUE TITLE
Led compatibility

### ISSUE THREAD

**Issue by Otann** [chestwood96/SlideSwipe#7]
I have a quick question, is this mod compatible with leds, which are mounted to the bottom of the Y extrusion?

[Like this one](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Jon/1515_led_mount)

**Comment by chestwood96** [comment]
Good question, depends on how far down the leds go and it would definitely
interfere with the stock wire routing.

**Comment by Otann** [comment]
I found that the answer is no, so I've designed [my own mount for led strips](https://www.printables.com/model/599080-voron-02-top-mounted-led) :)
All because I wanded the SlideSwipe so much.

Thank you for the amazing work! 🙌
