### ISSUE TITLE
V0.2 compatible mini SB cowling?

### ISSUE THREAD

**Issue by ulope** [chestwood96/SlideSwipe#8]
Do you have any plans to add a replacement cowling that fits the v0.2 Mini ~After~ Stealth Burner with the swappable hotend mounts?

Also thanks for making this cool mod!

**Comment by chestwood96** [comment]
You mean the minisb for the v0.2?

Personally I have no interest in the minisb(dragonburner is my preferred on
right now and that has native slideswipe support) but I think someone has
already put slideswipe on one, maybe I can dig that up.

**Comment by ulope** [comment]
Thanks, in the meantime I found a ready-made mod on Printables: https://www.printables.com/model/576996-voron-02-r1-slideswipe-mod

(And yeah I meant Mini SB not Mini AB)

**Comment by chestwood96** [comment]
Nice good to know, let me know how that works for you.
